id: IC1E957ED
legacy_id: P006680
ocr_import_info:
  bdrc_scan_id: W1AC220
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T01:03:24'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T16:01:29.221096+00:00'
last_modified: 2022-08-31 00:01:56.022804
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1AC220
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1AC220
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དྭགས་པོ་ཐར་རྒྱན།
  author: སྒམ་པོ་པ་བསོད་ནམས་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.855103327372948
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I4PD4471:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD4471
      total_pages: 470
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD4471.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.855103327372948
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
