id: IC1E957ED
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T01:06:10+00:00'
last_modified: '2022-06-08T06:05:53.247670+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC220
  title: 'དྭགས་པོ་ཐར་རྒྱན། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C607:
      image_group_id: I4PD4471
      title: ''
      total_pages: 470
      order: 1
      base_file: C607.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
